### ISSUE TITLE
Adding functionality for a .env file

### ISSUE THREAD

**Issue by 21isenough** [dennisreimann/stacking-sats-kraken#1]
Really like this script and intend to use it :fire: However, I know next to nothing about node.js, so please forgive my ignorance if this doesn't make sense. 

I installed this `dotenv` on my system and added to two lines below to the top of my `index.js` file. Not sure that's how this is done in node but it works for me. If I'd run a cron job I would want my `env vars` to be loaded somehow, right? :smiley: 

```
const dotenv = require('dotenv')
dotenv.config()
```

**Comment by dennisreimann** [comment]
Please see #2 on why I don‘t like to solve it this way. TL;DR I think the problem is easier to solve and I don‘t want to introduce a dependency for that.
