### ISSUE TITLE
Lightning withdrawals

### ISSUE THREAD

**Issue by menaceone** [dennisreimann/stacking-sats-kraken#17]
Hey Dennis,  
it would be very useful to withdraw the stacked sats via Lightning Network.  
I dug into the [Kraken API Doc](https://docs.kraken.com/rest/#tag/User-Funding/operation/withdrawFunds) and couldn't find anything about Lightning withdrawals.  
That would mean it can't be implemented in this project.  
  
Could you confirm that?

**Comment by dennisreimann** [comment]
Yes, afaik the Kraken API doesn't support Lightning withdarals yet.

**Comment by yoshimo** [comment]
```Unfortunately, BTC Lightning funding is not yet supported via our API, but our product/development teams are actively implementing this, so Lightning funding will be available via our API soon (perhaps by Q1 2023).```
According to their support team

**Comment by menaceone** [comment]
thx for your inputs. 👍 
So we have to wait for Kraken.
