### ISSUE TITLE
Allow withdrawal by address or extened public key

### ISSUE THREAD

**Issue by PatrickLemke** [dennisreimann/stacking-sats-kraken#3]
Currently this script can only be used to buy coins on Kraken.

It would be great if the functionality could be extended to also include automatic withdrawal to a user-specified address or extended public key.

**Comment by dennisreimann** [comment]
Unfortunately Kraken isn't really set up to fully automate the process, neither technically nor UX-wise: The API offers [some withdrawal functionality](https://www.kraken.com/features/api#withdraw-funds), but you'd have to reuse an address you specified before. The reason for that is that Kraken has a confirmation process for addresses, which is only accessible via their web interface and not automatable via the API.

Also Kraken charges a fee per withdrawal, which makes it hard if you want to be cost effective.
For now I think there is no other option than for this to be a manual process.

Nevertheless I'm already thinking about ways to extend the functionality and offer a way to grow this beyong single stacker usage: I imaginge a decentralized version one can host for family and friends – this way multiple people could not just share the costs but also gain privacy benefits, as the withdrawal goes to a single address which then does the payout to multiple participants.

**Comment by dennisreimann** [comment]
Update: #4
