### ISSUE TITLE
environment variable for crypto type

### ISSUE THREAD

**Issue by menaceone** [dennisreimann/stacking-sats-kraken#5]
Hey,
I just started to use your awesome script.

Currently the currency pair is only on the FIAT side configurable.
I would love to set an environment variable for crypto too.

If you want this as well, I could implement it and create a pull request.

greetings

**Comment by dennisreimann** [comment]
Hey, I kept it bitcoin specific for a reason – don't want to encourage buying shitcoins ;)

**Comment by menaceone** [comment]
okay, then I will make changes locally and use your repo as upstream.
